import React from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { Container, Button, Table } from 'react-bootstrap';

function Cart() {
  // Placeholder cart data (replace with context or API later)
    const cartItems = [];

      return (
          <>
                <Navbar />
                      <Container className="my-5">
                              <h3>Your Cart</h3>

                                      {cartItems.length === 0 ? (
                                                <p>Your cart is empty.</p>
                                                        ) : (
                                                                  <>
                                                                              <Table striped bordered hover responsive>
                                                                                            <thead>
                                                                                                            <tr>
                                                                                                                              <th>Product</th>
                                                                                                                                                <th>Qty</th>
                                                                                                                                                                  <th>Price</th>
                                                                                                                                                                                    <th>Subtotal</th>
                                                                                                                                                                                                      <th>Remove</th>
                                                                                                                                                                                                                      </tr>
                                                                                                                                                                                                                                    </thead>
                                                                                                                                                                                                                                                  <tbody>
                                                                                                                                                                                                                                                                  {cartItems.map((item, idx) => (
                                                                                                                                                                                                                                                                                    <tr key={idx}>
                                                                                                                                                                                                                                                                                                        <td>{item.name}</td>
                                                                                                                                                                                                                                                                                                                            <td>{item.qty}</td>
                                                                                                                                                                                                                                                                                                                                                <td>${item.price}</td>
                                                                                                                                                                                                                                                                                                                                                                    <td>${item.qty * item.price}</td>
                                                                                                                                                                                                                                                                                                                                                                                        <td><Button variant="danger" size="sm">X</Button></td>
                                                                                                                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                        </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Table>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="text-end">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h5>Total: $0.00</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Button variant="dark" href="/checkout">Go to Checkout</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Container>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Footer />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default Cart;