import React, { useState } from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { Container, Form, Button } from 'react-bootstrap';

function Signup() {
  const [form, setForm] = useState({
      name: '',
          email: '',
              password: '',
                });

                  const handleChange = (e) => {
                      setForm({ ...form, [e.target.name]: e.target.value });
                        };

                          const handleSignup = (e) => {
                              e.preventDefault();
                                  // Placeholder logic — replace with real API call
                                      alert(`Account created for: ${form.name}`);
                                        };

                                          return (
                                              <>
                                                    <Navbar />
                                                          <Container className="my-5" style={{ maxWidth: '500px' }}>
                                                                  <h3 className="mb-4">Sign Up</h3>
                                                                          <Form onSubmit={handleSignup}>
                                                                                    <Form.Group className="mb-3">
                                                                                                <Form.Label>Full Name</Form.Label>
                                                                                                            <Form.Control
                                                                                                                          type="text"
                                                                                                                                        name="name"
                                                                                                                                                      placeholder="Enter your name"
                                                                                                                                                                    value={form.name}
                                                                                                                                                                                  onChange={handleChange}
                                                                                                                                                                                                required
                                                                                                                                                                                                            />
                                                                                                                                                                                                                      </Form.Group>

                                                                                                                                                                                                                                <Form.Group className="mb-3">
                                                                                                                                                                                                                                            <Form.Label>Email Address</Form.Label>
                                                                                                                                                                                                                                                        <Form.Control
                                                                                                                                                                                                                                                                      type="email"
                                                                                                                                                                                                                                                                                    name="email"
                                                                                                                                                                                                                                                                                                  placeholder="Enter email"
                                                                                                                                                                                                                                                                                                                value={form.email}
                                                                                                                                                                                                                                                                                                                              onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                  </Form.Group>

                                                                                                                                                                                                                                                                                                                                                                            <Form.Group className="mb-4">
                                                                                                                                                                                                                                                                                                                                                                                        <Form.Label>Password</Form.Label>
                                                                                                                                                                                                                                                                                                                                                                                                    <Form.Control
                                                                                                                                                                                                                                                                                                                                                                                                                  type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                name="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="Create a password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={form.password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Form.Group>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Button variant="dark" type="submit" className="w-100">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Sign Up
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="mt-3 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Already have an account? <a href="/login">Login</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Container>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Footer />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default Signup;